site_name: MAP-ExPLoc
repo_url: https://github.com/cytronicoder/explainable-localization-predictor
nav:
  - Home: index.md
  - Quickstart: quickstart.md
  - API Reference: api.md
  - Adapter Guide: adapter-guide.md
  - Explainer Guide: explainer-guide.md
  - Reporting Schema: reporting-schema.md
  - UI Usage: ui.md
  - Migration: migration.md
  - Tutorials:
      - Preprocessing: tutorials/preprocessing.md
      - k-NN: tutorials/knn.md
      - Random Forest: tutorials/rf.md
      - SHAP: tutorials/shap.md
      - Exploratory: tutorials/exploratory.md
      - YBS Challenge: tutorials/ybs.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: numpy
markdown_extensions:
  - admonition
  - toc
  - tables
theme:
  name: material
